[build]
  # Directory to deploy the site from
  publish = "_site"
  # Command to build the site
  command = "bundle exec jekyll build"

[build.environment]
  # Set the Ruby version to match the .ruby-version file
  RUBY_VERSION = "3.1.3"
  BUNDLER_VERSION = "2.3.26" # Ensure to match the Bundler version in Gemfile.lock

[context.production.environment]
  # You can add production-specific environment variables here if needed
  JEKYLL_ENV = "production"

[context.deploy-preview]
  # Specific settings for preview deploys
  command = "bundle exec jekyll build"

[[plugins]]
  package = "@netlify/plugin-gatsby" # Example of a plugin; you can remove or change based on your needs
